# Generated by Django 5.0.1 on 2024-06-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_app_secret_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='app_secret_token',
            new_name='secret_token',
        ),
    ]
